'use client';
import Image from 'next/image';
import {AnimatePresence,motion} from 'framer-motion';
import {useEffect,useReducer,useState} from 'react';

const projects=[
 {name:'Aurum',place:'Салон красоты · Волгоград',year:'2026',url:'https://aurum-beauty-salon-l-uvr7.bolt.host/',task:'Сайт-визитка, который помогает быстро найти услуги, цены, адрес и записаться в один клик.',result:'Структура без лишнего: посетитель получает нужную информацию за несколько секунд и переходит к записи.',screens:Array.from({length:5},(_,i)=>`/media/portfolio/aurum/screen-${String(i+1).padStart(2,'0')}.png`)},
 {name:'СтильнаЯ',place:'Салон красоты · Волгоград',year:'2026',url:'https://stilnaya-site.vercel.app',task:'Сайт для салона с полным прайсом, акцией для новых клиентов, формой записи и ответами на вопросы.',result:'Собрал точки доверия: рейтинг и отзывы с Яндекс Карт, понятные услуги и быстрый путь к заявке.',screens:Array.from({length:10},(_,i)=>`/media/portfolio/stilnaya/screen-${String(i+1).padStart(2,'0')}.png`)},
 {name:'Лаборатория',place:'Детейлинг-студия · Волгоград',year:'2026',url:'https://laboratoriya-2.vercel.app',task:'Премиальный сайт-визитка, который помогает владельцу авто понять услуги, цены и уровень студии.',result:'Показал статус через бренды LLUMAR и KRYTEX, рейтинг 5.0 в 2ГИС, работы, прайс и форму записи.',screens:Array.from({length:9},(_,i)=>`/media/portfolio/laboratoriya/screen-${String(i+1).padStart(2,'0')}.png`)},
];
const benefits=[
 ['Задача бизнеса','Сначала разбираюсь, что сайт должен дать именно вашему бизнесу.'],
 ['Понятная структура','Клиент быстро находит услуги, цены и способ связи.'],
 ['Аккуратный дизайн','Сайт выглядит современно и подходит вашей сфере.'],
 ['Удобно с телефона','Все блоки и кнопки корректно работают на смартфоне.'],
 ['Связь в один клик','Заметные кнопки ведут клиента к звонку, заявке или Telegram.'],
 ['Можно дополнить позже','Сайт легко развивать: добавлять услуги, фото и новые разделы.'],
];
const quizQuestions=[
 {title:'Что вы хотите сделать?',options:[['Новый сайт-визитку','Коротко и понятно расскажет о вашей компании, услугах и контактах. От 9 000 ₽.',9000],['Страницу для одной услуги','Лендинг, который ведёт посетителя к заявке или покупке. От 12 000 ₽.',12000],['Улучшить текущий сайт','Обновить дизайн, тексты, формы или мобильную версию. От 6 000 ₽.',6000]]},
 {title:'Какая главная задача сайта?',options:[['Получать больше обращений','Чтобы клиент оставил заявку, позвонил или написал вам.',2000],['Показать услуги и цены','Чтобы люди быстро понимали, что вы предлагаете и сколько это стоит.',1000],['Выглядеть надёжнее конкурентов','Чтобы бизнес вызывал доверие с первого экрана.',1500]]},
 {title:'Что уже есть для сайта?',options:[['Тексты и фотографии готовы','Можно быстрее перейти к созданию сайта.',0],['Есть только часть информации','Помогу собрать и аккуратно оформить недостающие материалы.',1500],['Пока только идея','Разберёмся вместе: что рассказать и какие блоки нужны.',2500]]},
 {title:'Сколько информации нужно показать?',options:[['Одна страница','Например: услуга, преимущества, цены и форма связи.',0],['Несколько страниц','Например: главная, услуги, о компании и контакты.',2500],['Нужен совет','Подскажу оптимальную структуру после короткого созвона.',1000]]},
 {title:'Как клиентам будет удобнее связаться?',options:[['Позвонить или написать в Telegram','Добавим заметные кнопки связи на всех устройствах.',0],['Оставить заявку на сайте','Сделаем форму с понятными полями и уведомлением для вас.',1000],['Записаться на услугу','Добавим удобный сценарий записи и нужные контакты.',1500]]},
 {title:'Когда хотите запустить сайт?',options:[['Как можно скорее','Соберём минимально нужную версию и запустим поэтапно.',1000],['В течение 2–4 недель','Оптимальный темп: продуманная структура, дизайн и проверка.',500],['Пока изучаю варианты','Обсудим идею без спешки и составим понятный план.',0]]},
];
const steps=[
 ['Погружаемся','Знакомимся с бизнесом, услугой и вашей аудиторией.'],
 ['Формулируем задачу','Определяем, какое действие должен сделать посетитель.'],
 ['Собираем стратегию','Выстраиваем понятный путь от первого экрана до заявки.'],
 ['Создаём дизайн','Согласовываем аккуратный вид будущего сайта.'],
 ['Разрабатываем','Собираю сайт, который быстро работает на всех устройствах.'],
 ['Тестируем','Проверяю формы, ссылки и отображение на телефоне.'],
 ['Запускаем','Публикуем сайт и передаём вам готовый результат.'],
];
const faqs=[
 ['Сколько длится проект?','Большинство сайтов-визиток и лендингов я собираю примерно за 2–4 дня. Точный срок зависит от объёма задачи, количества блоков и того, готовы ли тексты с фотографиями. Перед началом работы сразу скажу, когда смогу показать готовый сайт.'],
 ['Как формируется стоимость?','Цена зависит не от сложных терминов, а от объёма работы: нужен ли новый сайт или доработка, сколько информации нужно разместить, нужны ли форма заявки, дополнительные страницы или помощь с материалами. Базовая стоимость указана на сайте, а точную сумму согласуем до начала работы.'],
 ['Можно начать с небольшой задачи?','Да. Не обязательно сразу заказывать большой сайт. Можно начать с доработки текущей страницы, новой формы заявки, обновления дизайна или отдельного лендинга для одной услуги. Это хороший способ сначала решить главную задачу и увидеть результат.'],
 ['Вы работаете после запуска?','После публикации я проверяю, что сайт открывается на телефоне, кнопки и формы работают, а ссылки ведут куда нужно. Если позже понадобятся небольшие изменения — например, заменить цену, добавить услугу или фото — можно написать мне и обсудить доработку.'],
];
function Reveal({children}:{children:React.ReactNode}){return <motion.div initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.15}} transition={{duration:.5}}>{children}</motion.div>}
function Placeholder({src,label,priority=false}:{src:string,label:string,priority?:boolean}){const [fail,setFail]=useState(false);return <div className="media h-full w-full" data-media={label}>{!fail&&<Image src={src} alt="" fill sizes="(max-width: 768px) 100vw, 50vw" priority={priority} className="object-cover" onError={()=>setFail(true)}/>}</div>}
type Quiz={step:number;answers:number[];contact:string};type Action={type:'next'|'back'|'answer'|'contact';value?:number|string};
function quizReducer(s:Quiz,a:Action):Quiz{if(a.type==='answer')return {...s,answers:[...s.answers,a.value as number],step:Math.min(6,s.step+1)};if(a.type==='next')return {...s,step:Math.min(6,s.step+1)};if(a.type==='back')return {...s,step:Math.max(0,s.step-1),answers:s.answers.slice(0,-1)};return {...s,contact:a.value as string}}
function Quiz(){const [state,dispatch]=useReducer(quizReducer,{step:0,answers:[],contact:''});const price=state.answers.reduce((a,b)=>a+b,0);if(state.step===6)return <div className="card p-6 md:p-10"><p className="eyebrow">Ваш ориентир</p><h3 className="text-4xl font-semibold">от {price.toLocaleString('ru-RU')} ₽</h3><p className="mt-4 max-w-lg leading-relaxed text-muted">Это предварительный ориентир. Напишите мне — уточним задачу, посмотрим ваш бизнес и я предложу точный объём работ без сложных терминов.</p><div className="mt-7 flex flex-wrap gap-3"><a className="btn btn-lime" href="https://t.me/NoAmm0" target="_blank" rel="noreferrer">Обсудить в Telegram</a><button className="btn" onClick={()=>dispatch({type:'back'})}>Изменить ответ</button></div></div>;const question=quizQuestions[state.step];return <div className="card p-6 md:p-10"><div className="mb-8 flex justify-between text-sm"><span>Вопрос {state.step+1} / 6</span><span>{Math.round(state.step/6*100)}%</span></div><h3 className="mb-7 text-3xl font-semibold">{question.title}</h3><div className="grid md:grid-cols-3">{question.options.map(([title,description,addition])=><button key={title} onClick={()=>dispatch({type:'answer',value:addition})} className="rounded-xl border border-line p-5 text-left transition hover:border-ink focus-visible:outline-2 focus-visible:outline-lime"><strong className="block text-lg">{title}</strong><span className="mt-3 block text-sm leading-relaxed text-muted">{description}</span></button>)}</div>{state.step>0&&<button className="mt-6 text-sm underline" onClick={()=>dispatch({type:'back'})}>← Вернуться к предыдущему вопросу</button>}</div>}
function ThemeToggle(){const [dark,setDark]=useState(false);useEffect(()=>{const saved=localStorage.getItem('theme');const next=saved==='dark';setDark(next);document.documentElement.classList.toggle('dark',next)},[]);const toggle=()=>{const next=!dark;setDark(next);document.documentElement.classList.toggle('dark',next);localStorage.setItem('theme',next?'dark':'light')};return <button type="button" onClick={toggle} className="grid h-10 w-10 shrink-0 place-items-center rounded-full border border-line transition hover:border-lime focus-visible:outline-2 focus-visible:outline-lime focus-visible:outline-offset-2" aria-label={dark?'Включить светлую тему':'Включить тёмную тему'} title={dark?'Светлая тема':'Тёмная тема'}>{dark?<svg viewBox="0 0 24 24" className="h-4 w-4" aria-hidden="true"><path fill="currentColor" d="M12 4.5a7.5 7.5 0 1 0 7.5 7.5A6 6 0 0 1 12 4.5Z"/></svg>:<svg viewBox="0 0 24 24" className="h-4 w-4" aria-hidden="true"><path fill="none" stroke="currentColor" strokeLinecap="round" strokeWidth="1.8" d="M12 3v2m0 14v2M3 12h2m14 0h2M5.6 5.6 7 7m10 10 1.4 1.4M18.4 5.6 17 7M7 17l-1.4 1.4"/><circle cx="12" cy="12" r="4" fill="none" stroke="currentColor" strokeWidth="1.8"/></svg>}</button>}
function Header(){const [open,setOpen]=useState(false);const links=[['Подход','services'],['Кейсы','cases'],['Этапы','blog'],['Контакты','contacts']];return <header className="sticky top-0 z-50 border-b border-line bg-paper/95 backdrop-blur"><div className="wrap flex h-16 items-center justify-between"><a href="#top" className="font-bold tracking-tight">WEB<span className="text-muted">/PORTFOLIO</span></a><nav className="hidden gap-7 text-sm md:flex" aria-label="Основная навигация">{links.map(([x,id])=><a key={id} href={`#${id}`} className="hover:underline">{x}</a>)}</nav><div className="flex items-center gap-2"><ThemeToggle/><a href="https://t.me/NoAmm0" target="_blank" rel="noreferrer" className="btn hidden py-2 md:inline-flex">Обсудить проект</a><button className="rounded p-2 md:hidden" aria-label="Открыть меню" aria-expanded={open} onClick={()=>setOpen(!open)}>☰</button></div></div><AnimatePresence>{open&&<motion.nav initial={{opacity:0,height:0}} animate={{opacity:1,height:'auto'}} exit={{opacity:0,height:'auto'}} className="wrap grid gap-4 overflow-hidden pb-5 md:hidden" aria-label="Мобильная навигация">{links.map(([x,id])=><a onClick={()=>setOpen(false)} href={`#${id}`} key={id}>{x}</a>)}</motion.nav>}</AnimatePresence></header>}
export default function Home(){const [faq,setFaq]=useState<number|null>(null);return <main id="top"><Header/><section className="wrap grid min-h-[calc(100vh-64px)] items-end gap-10 py-16 md:grid-cols-2 md:py-24"><Reveal><p className="eyebrow mb-5">Веб-разработка / 2026</p><h1 className="display mb-7 text-[clamp(3.25rem,5.5vw,6rem)] font-semibold">Сайт, который помогает выбрать вас.</h1><p className="max-w-md text-lg leading-relaxed text-muted">Создаю понятные сайты-визитки для локального бизнеса: услуги, цены, доверие и простой путь к заявке.</p><div className="mt-9 flex flex-wrap gap-3"><a className="btn btn-lime" href="#contacts">Обсудить проект</a><a className="btn" href="#cases">Смотреть работы</a></div></Reveal><div className="relative h-[360px] overflow-hidden rounded-2xl md:h-[640px]"><Image src="/media/hero/hero-laboratoriya-workspace.png" alt="Ноутбук с открытым сайтом детейлинг-студии Лаборатория" fill priority sizes="(max-width: 768px) 100vw, 50vw" className="object-cover"/></div></section>
<section id="services" className="section"><div className="wrap"><Reveal><p className="eyebrow">01 / Подход</p><h2 className="display mt-4 max-w-3xl text-5xl font-semibold md:text-7xl">Сайт по делу.</h2><p className="mt-6 max-w-xl text-lg leading-relaxed text-muted">Быстро собираю понятные сайты для услуг, чтобы клиенту было легко выбрать вас и связаться.</p></Reveal><div className="grid mt-12 sm:grid-cols-2 lg:grid-cols-3">{benefits.map(([title,description],i)=><Reveal key={title}><article className="card min-h-48 p-6"><span className="mb-8 block text-2xl" aria-hidden>0{i+1}</span><h3 className="text-xl font-semibold">{title}</h3><p className="mt-3 text-sm leading-relaxed text-muted">{description}</p></article></Reveal>)}</div></div></section>
<section className="section"><div className="wrap"><Reveal><p className="eyebrow">02 / О подходе</p><div className="mt-5 max-w-5xl"><h2 className="text-4xl font-semibold md:text-6xl">Не просто красивая страница.</h2><p className="mt-4 max-w-2xl text-lg leading-relaxed text-muted">Создаю сайты для услуг и локального бизнеса — понятные человеку, который видит вас впервые, и удобные для владельца бизнеса.</p><blockquote className="mt-10 max-w-4xl border-l-2 border-l-lime pl-6 text-2xl leading-snug md:text-3xl">«Сначала определяем, что должен сделать посетитель: узнать цену, выбрать услугу, оставить заявку или написать вам. Затем строим сайт вокруг этого действия.»</blockquote><p className="mt-8 max-w-3xl text-lg leading-relaxed text-muted">Вместе собираем основу: чем вы полезны клиенту, какие услуги важнее показать, где указать цены и как сделать связь быстрой. Я перевожу всё это в спокойную структуру, аккуратный дизайн и понятные кнопки — без сложных терминов и лишних экранов.</p><div className="mt-10 grid gap-4 md:grid-cols-3"><article className="card p-6"><p className="eyebrow">01 / Смысл</p><h3 className="mt-3 text-xl font-semibold">Показываю главное</h3><p className="mt-3 leading-relaxed text-muted">Клиент сразу видит, чем вы занимаетесь, сколько это стоит и почему стоит обратиться именно к вам.</p></article><article className="card p-6"><p className="eyebrow">02 / Удобство</p><h3 className="mt-3 text-xl font-semibold">Веду к связи</h3><p className="mt-3 leading-relaxed text-muted">Запись, звонок или Telegram находятся там, где они действительно нужны — на пути к решению.</p></article><article className="card p-6"><p className="eyebrow">03 / Результат</p><h3 className="mt-3 text-xl font-semibold">Собираю быстро</h3><p className="mt-3 leading-relaxed text-muted">Для небольшой задачи можно получить готовый аккуратный сайт за несколько дней, в зависимости от объёма.</p></article></div></div></Reveal></div></section>
<section id="cases" className="section"><div className="wrap"><p className="eyebrow">03 / Реальные проекты</p><div className="mt-4 max-w-4xl"><h2 className="display text-5xl font-semibold md:text-7xl">Сайты, которые ведут к заявке.</h2><p className="mt-6 max-w-xl text-lg leading-relaxed text-muted">Три сайта-визитки для локального бизнеса: от понятного прайса до формы записи и точек доверия.</p></div><div className="mt-16 space-y-24">{projects.map((p,index)=><article key={p.name} className="border-t border-line pt-6"><div className="grid gap-7 lg:grid-cols-[.75fr_1.25fr]"><div className="lg:sticky lg:top-24 lg:self-start"><p className="eyebrow">0{index+1} / {p.year}</p><h3 className="mt-3 text-4xl font-semibold">{p.name}</h3><p className="mt-2 text-sm text-muted">{p.place}</p><p className="mt-8 text-lg leading-relaxed">{p.task}</p><p className="mt-5 border-l-2 border-l-lime pl-4 text-sm leading-relaxed text-muted">{p.result}</p><a href={p.url} target="_blank" rel="noreferrer" className="btn btn-lime mt-8">Открыть сайт <span aria-hidden className="ml-2">↗</span></a></div><div className="grid gap-4 sm:grid-cols-2">{p.screens.map((screen,i)=><a href={p.url} target="_blank" rel="noreferrer" aria-label={`${p.name}, экран ${i+1}: открыть сайт`} key={screen} className={`block overflow-hidden rounded-xl border border-line bg-white ${i===0?'sm:col-span-2':''}`}><Image src={screen} alt={`Скриншот сайта ${p.name}: экран ${i+1}`} width={1870} height={900} sizes="(max-width: 640px) 100vw, 50vw" className="h-auto w-full transition duration-500 hover:scale-[1.02]"/></a>)}</div></div></article>)}</div></div></section>
<section id="quiz" className="section"><div className="wrap grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><Reveal><p className="eyebrow">04 / Калькулятор</p><h2 className="display mt-4 text-5xl font-semibold">Поймём масштаб.</h2><p className="mt-6 max-w-sm text-muted">Ответьте на шесть коротких вопросов — пришлём ориентир по бюджету.</p></Reveal><Quiz/></div></section>
<section className="section"><div className="wrap"><p className="eyebrow">05 / Процесс</p><ol className="mt-10 grid border-t border-line md:grid-cols-2 lg:grid-cols-4">{steps.map(([title,description],i)=><li key={title} className="border-b border-line py-7 pr-5"><span className="text-sm text-muted">0{i+1}</span><h3 className="mt-6 text-xl font-semibold">{title}</h3><p className="mt-2 text-sm leading-relaxed text-muted">{description}</p></li>)}</ol></div></section>
<section className="section"><div className="wrap"><p className="eyebrow">06 / Стоимость</p><h2 className="display mt-4 text-5xl font-semibold">Понятные форматы</h2><p className="mt-5 max-w-xl text-muted">Делаю быстро, аккуратно и без лишних затрат: большинство задач готово за 2–4 дня. Точный срок зависит от проекта.</p><div className="grid mt-12 lg:grid-cols-3"><article className="card p-7"><h3 className="text-2xl font-semibold">Сайт-визитка</h3><p className="mt-3 text-sm text-muted">Для компании, мастера или услуги: показать главное и дать клиенту способ связаться.</p><p className="mt-10 text-3xl font-semibold">от 9 000 ₽</p><p className="mt-2 text-sm text-muted">Срок: примерно 2–4 дня</p><details className="mt-7 border-t border-line pt-4"><summary className="cursor-pointer font-medium">Что входит</summary><ul className="mt-4 space-y-2 text-sm text-muted"><li>• Структура одной страницы</li><li>• Адаптация под телефон</li><li>• Контакты и кнопки связи</li></ul></details></article><article className="card p-7"><h3 className="text-2xl font-semibold">Лендинг</h3><p className="mt-3 text-sm text-muted">Для одной услуги, акции или предложения — с фокусом на заявку.</p><p className="mt-10 text-3xl font-semibold">от 12 000 ₽</p><p className="mt-2 text-sm text-muted">Срок: примерно 3–4 дня</p><details className="mt-7 border-t border-line pt-4"><summary className="cursor-pointer font-medium">Что входит</summary><ul className="mt-4 space-y-2 text-sm text-muted"><li>• Продающая структура</li><li>• Блоки доверия и услуг</li><li>• Форма заявки</li></ul></details></article><article className="card p-7"><h3 className="text-2xl font-semibold">Доработка сайта</h3><p className="mt-3 text-sm text-muted">Если сайт уже есть, но его нужно освежить, дополнить или исправить.</p><p className="mt-10 text-3xl font-semibold">от 6 000 ₽</p><p className="mt-2 text-sm text-muted">Срок: от 1 дня</p><details className="mt-7 border-t border-line pt-4"><summary className="cursor-pointer font-medium">Что входит</summary><ul className="mt-4 space-y-2 text-sm text-muted"><li>• Разбор текущего сайта</li><li>• Нужные правки</li><li>• Проверка после изменений</li></ul></details></article></div></div></section>
<section className="section"><div className="wrap"><p className="eyebrow">07 / Как строится работа</p><h2 className="display mt-4 max-w-3xl text-5xl font-semibold">Спокойно, прозрачно, по делу.</h2><div className="grid mt-10 gap-4 md:grid-cols-3"><article className="card p-7"><span className="eyebrow">01</span><h3 className="mt-6 text-xl font-semibold">Сначала разбираюсь</h3><p className="mt-3 leading-relaxed text-muted">Обсуждаем вашу услугу, клиента и цель сайта — чтобы не делать экраны «просто для красоты».</p></article><article className="card p-7"><span className="eyebrow">02</span><h3 className="mt-6 text-xl font-semibold">Показываю ход работы</h3><p className="mt-3 leading-relaxed text-muted">Согласовываем структуру и дизайн поэтапно. Вы понимаете, что и зачем появляется на сайте.</p></article><article className="card p-7"><span className="eyebrow">03</span><h3 className="mt-6 text-xl font-semibold">Довожу до запуска</h3><p className="mt-3 leading-relaxed text-muted">Проверяю мобильную версию, формы и ссылки, чтобы сайт был готов принимать обращения.</p></article></div></div></section>
<section id="blog" className="section"><div className="wrap"><p className="eyebrow">08 / Полезное перед стартом</p><div className="mt-4 max-w-2xl"><h2 className="display text-5xl font-semibold">Без сложных слов о сайте.</h2><p className="mt-5 leading-relaxed text-muted">Три внешних материала для тех, кто хочет разобраться в задаче до первого созвона.</p></div><div className="grid mt-10 gap-6 md:grid-cols-3"><article><div className="aspect-[16/10] overflow-hidden rounded-xl bg-black"><iframe className="h-full w-full" loading="lazy" src="https://www.youtube-nocookie.com/embed/aOfckmqtdAM" title="Как сделать сайт для бизнеса — пошаговая инструкция" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen/></div><p className="mt-4 text-sm text-muted">Видео · YouTube</p><h3 className="mt-2 text-xl font-semibold">Как сделать сайт для бизнеса: пошаговая инструкция</h3><p className="mt-3 text-sm leading-relaxed text-muted">Разбор пути от идеи до запуска: домен, структура, дизайн и базовая настройка.</p><a className="mt-4 inline-block text-sm underline" href="https://www.youtube.com/watch?v=aOfckmqtdAM" target="_blank" rel="noreferrer">Смотреть на YouTube ↗</a></article><article className="card p-6"><span className="text-3xl" aria-hidden>01</span><p className="mt-8 text-sm text-muted">Статья · Tilda Education</p><h3 className="mt-2 text-xl font-semibold">Этапы разработки сайта: от идеи до реализации</h3><p className="mt-3 text-sm leading-relaxed text-muted">Объясняет, из каких этапов складывается создание сайта и почему сначала важна задача бизнеса, а не дизайн.</p><a className="mt-5 inline-block text-sm underline" href="https://tilda.education/website-development-process-in-agency" target="_blank" rel="noreferrer">Читать статью ↗</a></article><article className="card p-6"><span className="text-3xl" aria-hidden>02</span><p className="mt-8 text-sm text-muted">Статья · Бизнес-секреты</p><h3 className="mt-2 text-xl font-semibold">Как создать сайт для бизнеса с нуля</h3><p className="mt-3 text-sm leading-relaxed text-muted">Практический гид: как определить цель сайта, выбрать формат и подготовить информацию для запуска.</p><a className="mt-5 inline-block text-sm underline" href="https://secrets.tbank.ru/biznes-s-nulya/sdelat-sajt/" target="_blank" rel="noreferrer">Читать статью ↗</a></article></div></div></section>
<section className="section"><div className="wrap max-w-3xl"><p className="eyebrow">09 / FAQ</p><h2 className="display mt-4 text-5xl font-semibold">Частые вопросы</h2><div className="mt-10 border-t border-line">{faqs.map(([question,answer],i)=><div className="border-b border-line" key={question}><button className="flex w-full items-center justify-between py-5 text-left font-medium" aria-expanded={faq===i} onClick={()=>setFaq(faq===i?null:i)}>{question}<span aria-hidden>{faq===i?'−':'+'}</span></button><AnimatePresence>{faq===i&&<motion.p initial={{height:0,opacity:0}} animate={{height:'auto',opacity:1}} exit={{height:0,opacity:0}} className="overflow-hidden pb-5 leading-relaxed text-muted">{answer}</motion.p>}</AnimatePresence></div>)}</div></div></section>
<section id="contacts" className="section"><div className="wrap grid gap-10 rounded-3xl bg-ink p-7 text-paper md:grid-cols-2 md:p-14"><div><p className="eyebrow text-[#bfc0b7]">10 / Контакт</p><h2 className="display mt-5 text-5xl font-semibold md:text-7xl">Давайте начнём.</h2><p className="mt-6 max-w-sm text-[#bfc0b7]">Расскажите о задаче — отвечу, задам нужные вопросы и предложу понятный следующий шаг.</p><div className="mt-8 grid gap-4"><a className="group flex w-fit items-center gap-3 text-lg hover:text-lime focus-visible:outline focus-visible:outline-lime" href="https://t.me/NoAmm0" target="_blank" rel="noreferrer" aria-label="Написать мне в Telegram"><span className="grid h-10 w-10 place-items-center rounded-full bg-lime text-ink" aria-hidden><svg viewBox="0 0 24 24" className="h-5 w-5 fill-current"><path d="M21.9 3.5 18.6 20c-.2 1.2-.9 1.5-1.8.9l-5-3.7-2.4 2.3c-.3.3-.5.5-1 .5l.4-5 9.1-8.2c.4-.4-.1-.6-.6-.3L6.1 13.6 1.3 12.1c-1-.3-1-1 .2-1.5L20.2 3.4c.9-.3 1.7.2 1.7 1.1Z"/></svg></span><span className="underline decoration-white/40 underline-offset-4 group-hover:decoration-lime">Напишите мне в Telegram</span><span aria-hidden>↗</span></a><a className="group flex w-fit items-center gap-3 text-lg hover:text-lime focus-visible:outline focus-visible:outline-lime" href="mailto:danilsever522@gmail.com" aria-label="Написать мне по электронной почте"><span className="grid h-10 w-10 place-items-center rounded-full border border-paper/40" aria-hidden><svg viewBox="0 0 24 24" className="h-5 w-5 fill-current"><path d="M3 5h18v14H3V5Zm2 2v.5l7 4.7 7-4.7V7H5Zm14 10V9.9l-6.4 4.3a1 1 0 0 1-1.2 0L5 9.9V17h14Z"/></svg></span><span className="underline decoration-white/40 underline-offset-4 group-hover:decoration-lime">Напишите мне на почту</span><span aria-hidden>↗</span></a></div></div><form className="grid gap-4" onSubmit={e=>{e.preventDefault();window.location.href='https://t.me/NoAmm0'}}><label className="text-sm">Что нужно сделать?<textarea required className="mt-2 min-h-24 w-full rounded-lg border border-[#54554d] bg-transparent p-3" placeholder="Например: сайт-визитка для студии"/></label><label className="text-sm">Бюджет<select className="mt-2 w-full rounded-lg border border-[#54554d] bg-ink p-3"><option>Выберите диапазон</option><option>до 50 000 ₽</option><option>50 000–100 000 ₽</option><option>от 100 000 ₽</option></select></label><label className="text-sm">Способ связи<input required className="mt-2 w-full rounded-lg border border-[#54554d] bg-transparent p-3" placeholder="Email или Telegram"/></label><button className="btn btn-lime mt-2 w-fit" type="submit">Написать в Telegram</button></form></div></section>
<footer className="wrap py-12"><div className="grid gap-8 md:grid-cols-4"><div><p className="font-bold">WEB/PORTFOLIO</p><p className="mt-3 text-sm text-muted">Сайты для услуг<br/>© 2026</p></div>{[['Услуги',['Сайты-визитки','Лендинги','Доработка сайтов']],['Информация',['О подходе','Кейсы','Контакты']],['Связь',['Telegram @NoAmm0','Email']]].map(([h,links])=><div key={h as string}><h3 className="text-sm font-semibold">{h as string}</h3>{(links as string[]).map(x=><a href={x.includes('Telegram')?'https://t.me/NoAmm0':x==='Email'?'mailto:danilsever522@gmail.com':'#top'} className="mt-3 block text-sm text-muted hover:underline" key={x}>{x}</a>)}</div>)}</div><div className="mt-12 flex flex-wrap justify-between gap-4 border-t border-line pt-5 text-xs text-muted"><a href="mailto:danilsever522@gmail.com">danilsever522@gmail.com</a><a href="https://t.me/NoAmm0" target="_blank" rel="noreferrer">@NoAmm0 в Telegram</a></div></footer></main>}
